# 1. Chọn image Node.js
FROM node:20-alpine

# 2. Tạo thư mục làm việc
WORKDIR /app

# 3. Copy package.json và package-lock.json
COPY package*.json ./

# 4. Cài dependencies
RUN npm install --production

# 5. Copy toàn bộ source code
COPY . .

# 6. Expose cổng (cổng bạn chạy server)
EXPOSE 8082

# 7. Chạy server
CMD ["node", "src/app.js"]